Mantto/ControlAsistenciaFinal/src/java/com/control/asistencia/beans/BeanCuentas.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.control.asistencia.beans;

import com.control.asistencia.mantenimiento.CuentasJpaController;
import com.control.asistencia.mantenimiento.EncargadosJpaController;
import com.control.asistencia.mantenimiento.PersonalAcademicoJpaController;
import com.control.asistencia.mantenimiento.PersonasJpaController;
import com.control.asistencia.mantenimiento.TiposCuentasJpaController;
import com.control.asistencia.persistencias.Cuentas;
import com.control.asistencia.persistencias.Encargados;
import com.control.asistencia.persistencias.PersonalAcademico;
import com.control.asistencia.persistencias.Personas;
import com.control.asistencia.persistencias.TiposCuentas;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import org.primefaces.PrimeFaces;

/**
 *
 * @author luis.castillousam
 */
@ManagedBean
@RequestScoped
public class BeanCuentas implements Serializable {

    public BeanCuentas() {
    }

    public Cuentas getCuentas() {
        return cuentas;
    }

    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }

    public Personas getObPersona() {
        return obPersona;
    }

    public void setObPersona(Personas obPersona) {
        this.obPersona = obPersona;
    }

    public TiposCuentas getTipo() {
        return tipo;
    }

    public void setTipo(TiposCuentas tipo) {
        this.tipo = tipo;
    }

    public Encargados getObjEncargados() {
        return objEncargados;
    }

    public void setObjEncargados(Encargados objEncargados) {
        this.objEncargados = objEncargados;
    }

    public ArrayList getCuentasArrayList() {
        return cuentasArrayList;
    }

    public void setCuentasArrayList(ArrayList cuentasArrayList) {
        this.cuentasArrayList = cuentasArrayList;
    }

    public ArrayList getTiposCuentaArrayList() {
        return tiposCuentaArrayList;
    }

    public void setTiposCuentaArrayList(ArrayList tiposCuentaArrayList) {
        this.tiposCuentaArrayList = tiposCuentaArrayList;
    }

    public CuentasJpaController getConcuentas() {
        return concuentas;
    }

    public void setConcuentas(CuentasJpaController concuentas) {
        this.concuentas = concuentas;
    }

    public PersonasJpaController getConPersonas() {
        return conPersonas;
    }

    public void setConPersonas(PersonasJpaController conPersonas) {
        this.conPersonas = conPersonas;
    }

    public TiposCuentasJpaController getContipo() {
        return contipo;
    }

    public void setContipo(TiposCuentasJpaController contipo) {
        this.contipo = contipo;
    }

    public EncargadosJpaController getConEncargados() {
        return conEncargados;
    }

    public void setConEncargados(EncargadosJpaController conEncargados) {
        this.conEncargados = conEncargados;
    }

    private PersonalAcademico personalAcademico = new PersonalAcademico();
    private PersonalAcademicoJpaController pac = new PersonalAcademicoJpaController();
    private Cuentas cuentas = new Cuentas();
    private Personas obPersona = new Personas();
    private TiposCuentas tipo = new TiposCuentas();
    private Encargados objEncargados = new Encargados();
    private ArrayList cuentasArrayList = new ArrayList();
    private ArrayList tiposCuentaArrayList = new ArrayList();
    private CuentasJpaController concuentas = new CuentasJpaController();
    private PersonasJpaController conPersonas = new PersonasJpaController();
    private TiposCuentasJpaController contipo = new TiposCuentasJpaController();
    private EncargadosJpaController conEncargados = new EncargadosJpaController();

    public void clean() {
        cuentas = new Cuentas();
        tipo = new TiposCuentas();
        obPersona = new Personas();
        objEncargados = new Encargados();

        PrimeFaces.current().executeScript("PF('modalData').show();");
        PrimeFaces.current().ajax().update("formCuenta");
    }

    public ArrayList<TiposCuentas> mostrarTipos() {
        List<TiposCuentas> cuentaslList = contipo.mostrarTodo();
        tiposCuentaArrayList = new ArrayList();
        Iterator it = cuentaslList.iterator();

        while (it.hasNext()) {
            TiposCuentas t = (TiposCuentas) it.next();
            tiposCuentaArrayList.add(t);
        }
        return tiposCuentaArrayList;
    }

    public ArrayList<Cuentas> mostrarCuentas() {
        List<Cuentas> cuentasList = concuentas.mostrarTodo();
        cuentasArrayList = new ArrayList();
        Iterator it = cuentasList.iterator();
        while (it.hasNext()) {
            Cuentas ct = (Cuentas) it.next();
            cuentasArrayList.add(ct);
        }
        return cuentasArrayList;
    }

    public void dataCuentas() {
        cuentas.setTipoCuenta(tipo);
        if (cuentas.getIdCuenta() != null) {
            concuentas.editar(cuentas);
            obPersona.setIdCuenta(cuentas);
            conPersonas.editar(obPersona);

            FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Cambios Guardados", "");
            FacesContext.getCurrentInstance().addMessage(null, msg);
            PrimeFaces.current().ajax().update("formCuenta:table");
        } else {
            concuentas.crear(cuentas);  //Nueva Cuenta
            int idmax = concuentas.selectMax();

            cuentas = new Cuentas();
            cuentas.setIdCuenta(idmax);

            obPersona.setIdCuenta(cuentas);
            conPersonas.crear(obPersona);   //NUeva Persona
            if (cuentas.getTipoCuenta().getIdCuenta().equals(1)) {
                personalAcademico.setIdPersona(obPersona);
                pac.crear(personalAcademico);

                FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Se Agregó con Éxito", "");
                FacesContext.getCurrentInstance().addMessage(null, msg);
                PrimeFaces.current().ajax().update("formCuenta:table");
            } else {
                FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Se Agregó con Éxito", "");
                FacesContext.getCurrentInstance().addMessage(null, msg);
                PrimeFaces.current().ajax().update("formCuenta:table");
            }
        }
    }

    //Metodo de llenar ID
    public void cuentasperID(Personas a) {
        try {
            Cuentas obCt = new Cuentas();
            obCt.setIdCuenta(a.getIdCuenta().getIdCuenta());
            cuentas = concuentas.encontrar(obCt.getIdCuenta());
            tipo = cuentas.getTipoCuenta();
            System.out.println("A mitad");
            Personas obper = new Personas();
            obper.setIdPersona(a.getIdPersona());

            obPersona = conPersonas.encontrar(obper.getIdPersona());
            PrimeFaces.current().executeScript("PF('modalData').show();");
            PrimeFaces.current().ajax().update("formCuenta");
        } catch (Exception e) {
            System.out.println("Error al llenar, cuenta por: " + e.getMessage());
        }

    }

    //Se elimina la persona y su cuenta
    public void destroyCuenta(Personas a) {
        Cuentas cu = new Cuentas();
        Encargados enca = new Encargados();
        try {
            int id = a.getIdCuenta().getIdCuenta();
            cu.setIdCuenta(id);
            concuentas.eliminar(cu);

            PrimeFaces.current().ajax().update("formCuenta");
        } catch (Exception e) {
            System.out.println("Error al eliminar, Cuenta por: " + e.getMessage());
        }

    }

    public boolean isDisable() {
        return FacesContext.getCurrentInstance().getRenderResponse();
    }

    public void valute() {
        FacesMessage msg = null;
        boolean valuteIn;

        if (this.obPersona.getIdPersona() == null || this.objEncargados.getIdEncargado() == null
                || this.cuentas.getIdCuenta() == null || this.tipo.getIdCuenta() == null) {
            valuteIn = false;
            msg = new FacesMessage(FacesMessage.SEVERITY_WARN, "Error", "Todos los campos son requeridos");
            FacesContext.getCurrentInstance().addMessage(null, msg);
        } else {
            valuteIn = true;
            dataCuentas();
        }
        PrimeFaces.current().ajax().addCallbackParam("valuteIn", valuteIn);
    }
}

Mantto/ControlAsistenciaFinal/web/Acerca_de.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Acerca de</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"></link>
        <h:outputStylesheet name="/css/cssgenerico.css" />
        <h:outputStylesheet name="/css/btnStyle2.css" />
        <h:outputStylesheet name="/css/bootstrap.min.css"/>
        <h:outputStylesheet name="/css/body.css"/>
        <h:outputScript name="/js/menu.js" ></h:outputScript>
        <h:outputStylesheet name="/css/btnMedia.css" ></h:outputStylesheet>
    </h:head>
    <h:body style="background-image:url(#{request.contextPath}/resources/images/pantalla3.jpg);" >
        <h:form>
            <p:growl id="msg" ></p:growl>

            <p:menubar  >
                <p:menuitem class="disabled"     >
                    <div id="content">
                        <img src="#{request.contextPath}/resources/images/puntualidad.png" class="disabled" width="60" height="60"   />
                    </div>
                </p:menuitem>
                <p:menuitem  outcome="Contáctanos.xhtml"  style="margin-left: 100px !important;"  value="Contáctanos"   />
                <p:menuitem   value="Acerca de"  outcome="Acerca_de.xhtml" />
                <p:menuitem  class="disabled" >
                    <h:outputLabel  value="#{beanLogin.obPersonas.nombre} #{beanLogin.obPersonas.apellido}"   ></h:outputLabel>
                </p:menuitem>
                <p:menuitem >
                    <p:commandLink id="togglebar" oncomplete="PF('side').show();" style=" margin-left: 600px;" >  <i style="color:  white ;" class=" fas fa-bars fa-2x"></i></p:commandLink>
                </p:menuitem>
            </p:menubar>

            <p:sidebar  style="background-image:url(#{request.contextPath}/resources/images/pantalla3.jpg);" widgetVar="side" position="right">
                <p:commandLink oncomplete="PF('side').hide();" style=" color: white !important; margin-left: -220px; font-size: 20px !important;"  > <i class="fas fa-times fa-2x"></i></p:commandLink>
                <p:panelMenu style="width:250px; margin-top: 180px; "   >
                    <p:submenu label=" Mi Cuenta" style=" color:white! important; text-shadow:none! important;  ">
                        <p:menuitem value="Cambiar de Foto" style=" color:white ! important;" />
                        <p:menuitem value="Cambiar Contraseña" style=" color:white ! important;"  />
                        <p:menuitem value="Correos"  outcome="Notificaciones.xhtml" style=" color:white ! important;" />
                    </p:submenu>
                    <p:separator/>
                </p:panelMenu>
                <br/><br/><br/><br/><br/><br/><br/><br/><br/>
                <p:commandButton value="Cerrar Sesión" action="#{beanLogin.logOut()}" class="btn1" style=" width:180px !important; height:60px!important;  " ></p:commandButton>
                <p:graphicImage name="/images/user.png" width="120" height="120" style=" position: absolute; top:45px; right: 100px;  " ></p:graphicImage>
            </p:sidebar>
            <br/>            

            <p:graphicImage name="/images/gemas.png" width="1000" ></p:graphicImage>

            <div style="position: absolute; top: 29%; left: 17.5%; width: 130px; height: 130px; box-shadow: -4px -15px 40px #cc00ff,4px 15px 40px #cc00ff; border-radius: 50%">
                <p:graphicImage name="/images/anonimus.png" width="130" style=" border-radius: 50%" ></p:graphicImage> 
            </div>   

            <div style="position: absolute; top: 29%; left: 28.5%; width: 120px; height: 120px; box-shadow: -4px -15px 40px #ff8300,4px 15px 40px #ff8300; border-radius: 50%">
                <p:graphicImage name="/images/foto3.jpg" width="120" style=" border-radius: 50%" ></p:graphicImage> 
            </div>
            <div style="position: absolute; top: 29%; left: 40.5%; width: 130px; height: 130px; box-shadow: -4px -15px 40px #f7ff00,4px 15px 40px #f7ff00; border-radius: 50%">
                <p:graphicImage name="/images/foto1.jpeg" width="130" style=" border-radius: 50%" ></p:graphicImage> 
            </div>

            <div style="position: absolute; top: 29%; left: 51.5%; width: 130px; height: 130px; box-shadow: -4px -15px 40px #00ff73,4px 15px 40px #00ff73; border-radius: 50%">
                <p:graphicImage name="/images/foto4.jpg" width="130" style=" border-radius: 50%" ></p:graphicImage> 
            </div>

            <div style="position: absolute; top: 29%; left: 62.5%; width: 130px; height: 130px; box-shadow: -4px -15px 40px #1700ff,4px 15px 40px #03a9f4; border-radius: 50%">
                <p:graphicImage name="/images/foto2.jpg" width="130" style=" border-radius: 50%" ></p:graphicImage> 
            </div>

            <div style="position: absolute; top: 29%; left: 75%; width: 130px; height: 130px; box-shadow: -4px -15px 40px #ff0000,4px 15px 40px #ff0000; border-radius: 50%">
                <p:graphicImage name="/images/anonimus.png" width="130" style=" border-radius: 50%" ></p:graphicImage> 
            </div>
            <p:outputLabel value="Esta Aplicacion fue desarrollada por:" style="position:absolute; top: 15%; left: 25%; color:white; font-size: 40px;  " ></p:outputLabel>

            <br/><br/><br/>
            <div class="footer">  <!--comienzael footer-->
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="box-footer" >  <!--comienza la historia de la cruz roja en le footer-->

                            <h1>Control de Asistencia</h1>
                            <p:separator/>
                            <div class="history">    
                                <p>Este es un Sistema diseñado con la idea de llevar un control presiso de la Asistencia, al mismo tiempo proporcionar al padre de familia 
                                    una herramienta para monitorear la asistencia de sus hijos, asegurando una buena educacion.
                                </p>
                            </div>
                        </div>     
                        <div class="box-footer a"> <!--comienza las noticias del footer-->
                            <h1>Redes Sociales</h1> 
                            <p:separator/>
                            <div class="history">  <!--comienzo Redes Sociales del footer-->
                                <div >
                                    <a class="btnM" href="#"  >
                                        <i class="fab fa-facebook-f"  ></i>
                                    </a>
                                    <a class="btnM" href="#">
                                        <i class="fab fa-twitter"></i>
                                    </a>
                                    <a class="btnM" href="#">
                                        <i class="fab fa-google"></i>
                                    </a>
                                    <a class="btnM" href="#">
                                        <i class="fab fa-instagram"></i>
                                    </a>
                                    <a class="btnM" href="#">
                                        <i class="fab fa-youtube"></i>
                                    </a>
                                </div>        
                            </div>             <!--FIn Redes Sociales del footer-->    
                            <p:separator/>
                        </div>
                        <div class="box-footer"> <!--comienzel slider del footer-->
                            <h1>Galeria</h1> 
                            <p:separator/>
                            <div id="slider">
                                <figure>
                                    <p:link title="Ir a la noticia" href="https://www.elsalvador.com/fotogalerias/noticias-fotogalerias/575437/imagenes-historicas-de-la-cruz-roja-salvadorena-en-su-134-aniversario/">
                                        <img src="#{request.contextPath}/resources/slider/imgmini1.png" />    
                                        <img src="#{request.contextPath}/resources/slider/imgmini2.jpg" />
                                        <img src="#{request.contextPath}/resources/slider/imgmini3.JPG" />
                                        <img src="#{request.contextPath}/resources/slider/imgmini4.jfif" />
                                        <img src="#{request.contextPath}/resources/slider/imgmini5.png" />

                                    </p:link>
                                </figure>
                            </div>
                        </div>
                        <div class="copy-right"> <!--comienza el copyright-->
                            <p:separator/>
                            <h3 >Sistema de Control de Asistencia Copyright © 2019. Todos los derechos reservados</h3>
                            <p:separator/><br/>
                        </div>
                    </div> 
                </div>   
            </div> <!--termina el footer-->
        </h:form>
    </h:body>
</html>

Mantto/ControlAsistenciaFinal/web/Persona.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Persona</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"></link>
        <h:outputStylesheet name="/css/btnMedia.css"/>
        <h:outputStylesheet name="/css/cssgenerico.css" />
        <h:outputStylesheet name="/css/btnStyle2.css" />
        <h:outputStylesheet name="/css/bootstrap.min.css"/>
        <h:outputStylesheet name="/css/body.css"/>
        <script type="text/javascript">
            function handleValuteRequest(xhr, status, args) {
                if (args.validationFailed || !args.valuteIn) {
                    PF('modal').jq.effect("shake", {times: 5}, 10);
                } else {
                    PF('modal').hide();
                    $('#valuteLink').fadeOut();
                }
            }
        </script>

    </h:head>
    <h:body style="background-image:url(#{request.contextPath}/resources/images/pantalla3.jpg);" >
        <h:form id="form">
            <p:growl id="growl" showDetail="true" life="2000"></p:growl>
            <p:menubar  >
                <p:menuitem class="disabled"     >
                    <div id="content">
                        <img src="#{request.contextPath}/resources/images/puntualidad.png" class="disabled" width="60" height="60"   />
                    </div>
                </p:menuitem>
                <p:menuitem  outcome="Contáctanos.xhtml"  style="margin-left: 100px !important;"  value="Contáctanos"   />
                <p:menuitem   value="Acerca de"  outcome="Acerca_de.xhtml" />
                <p:menuitem  class="disabled" >
                    <h:outputLabel  value="#{beanLogin.obPersonas.nombre} #{beanLogin.obPersonas.apellido}"   ></h:outputLabel>
                </p:menuitem>
                <p:menuitem >
                    <p:commandLink id="togglebar" oncomplete="PF('side').show();" style=" margin-left: 600px;" >  <i style="color:  white ;" class=" fas fa-bars fa-2x"></i></p:commandLink>
                </p:menuitem>
            </p:menubar>
            <p:sidebar  style="background-image:url(#{request.contextPath}/resources/images/pantalla3.jpg);" widgetVar="side" position="right">
                <p:commandLink oncomplete="PF('side').hide();" style=" color: white !important; margin-left: -220px; font-size: 20px !important;"  > <i class="fas fa-times fa-2x"></i></p:commandLink>
                <p:panelMenu style="width:250px; margin-top: 180px; "   >
                    <p:submenu label=" Mi Cuenta" style=" color:white! important; text-shadow:none! important;  ">
                        <p:menuitem value="Cambiar de Foto" style=" color:white ! important;" />
                        <p:menuitem value="Cambiar Contraseña" style=" color:white ! important;"  />
                        <p:menuitem value="Correos"  style=" color:white ! important;" />
                    </p:submenu>
                    <p:separator/>
                </p:panelMenu>
                <br/><br/><br/><br/><br/><br/><br/><br/><br/>
                <p:commandButton value="Cerrar Sesión" action="#{beanLogin.logOut()}" class="btn1" style=" width:180px !important; height:40px!important;  " ></p:commandButton>
            </p:sidebar>

            <center>
                <div class="container">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
                        <p:panel header="Control de Personas" class="panel">
                            <f:facet name="actions" >
                                <p:commandLink value=" Regresar" action="Administrativo?faces-redirect=true"  style=" color: white !important" class="fas fa-undo-alt linkformat "  ></p:commandLink>
                            </f:facet>
                            <f:facet name="actions" >
                                <p:commandLink value=" Agregar" style="color: white;" class="fas fa-plus-circle linkformat " action="#{beanPersona.clean()}" ></p:commandLink>
                            </f:facet>

                            <p:dataTable value="#{beanPersona.mostrarPersonas()}" var="a"  rows="8" paginator="true" reflow="true" >
                                <p:column headerText="Id" width="45">
                                    <p:outputLabel  value="#{a.idPersona}" ></p:outputLabel>
                                </p:column>

                                <p:column headerText="Nombre" >
                                    <p:outputLabel value="#{a.nombre} #{a.apellido}"></p:outputLabel>
                                </p:column>

                                <p:column headerText="Fecha de Nacimiento" >

                                    <h:outputText value="#{a.fechaNac}"  >
                                        <f:convertDateTime pattern="yyyy-MM-dd" timeZone="America/El_Salvador"/>
                                    </h:outputText>

                                </p:column>

                                <p:column headerText="Direccion" >
                                    <p:outputLabel value="#{a.direccion}" ></p:outputLabel>
                                </p:column>

                                <p:column headerText="Eliminar" >
                                    <p:commandButton value="Eliminar" action="#{beanPersona.eliminarper(a)}" class="btn1" ></p:commandButton>
                                </p:column>

                                <p:column headerText="Editar" >
                                    <p:commandButton class="btn1" action="#{beanPersona.personaperId(a.idPersona)}" value="Editar" ></p:commandButton>
                                </p:column>
                            </p:dataTable>
                        </p:panel>
                        <p:dialog header="Personas" modal="true" widgetVar="modal" hideEffect="explode" 
                                  resizable="false" visible="#{not empty facesContext.messageList}">
                            <p:panelGrid columns="2" styleClass="ui-panelgrid-blank" >

                                <p:outputLabel value="Id:" />
                                <p:inputText readonly="#{beanCuentas.disable}" value="#{beanPersona.obPersona.idPersona}" ></p:inputText>

                                <p:outputLabel value="Nombre:" />
                                <p:inputText  value="#{beanPersona.obPersona.nombre}"></p:inputText>

                                <p:outputLabel value="Apellido:" />
                                <p:inputText  value="#{beanPersona.obPersona.apellido}" ></p:inputText>

                                <p:outputLabel value="Fecha de Nacimiento:" />
                                <p:calendar  value="#{beanPersona.obPersona.fechaNac}"  navigator="true"  pattern="yyyy-MM-dd" showOn="button" ></p:calendar>

                                <p:outputLabel value="Dirección:" />
                                <p:inputText  value="#{beanPersona.obPersona.direccion}"  ></p:inputText>
                                <h:inputHidden value="#{beanPersona.obCuentas.idCuenta}"/>
                            </p:panelGrid>  
                            <div class="p-grid p-dir-col">
                                <div class="p-col">
                                    <div class="box">
                                        <p:commandButton class="btn1" value="Cancelar" onclick="PF('modal').hide();" ></p:commandButton>
                                        <p:commandButton class="btn1" value="Continuar"  action="#{beanPersona.valute()}" 
                                                         update="growl" oncomplete="handleValuteRequest(xhr, status, args)"></p:commandButton>
                                    </div>
                                </div>
                            </div>    
                        </p:dialog>
                    </div>
                    <div class="col-lg-2">
                    </div>
                </div>
            </center>
        </h:form>
        <br></br><br/><br></br><br/>
        <div class="footer">  <!--comienzael footer-->
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="box-footer" >  <!--comienza la historia de la cruz roja en le footer-->

                        <h1>Control de Asistencia</h1>
                        <p:separator/>
                        <div class="history">    
                            <p>Este es un Sistema diseñado con la idea de llevar un control presiso de la Asistencia, al mismo tiempo proporcionar al padre de familia 
                                una herramienta para monitorear la asistencia de sus hijos, asegurando una buena educacion.
                            </p>
                        </div>
                    </div>     
                    <div class="box-footer a"> <!--comienza las noticias del footer-->
                        <h1>Redes Sociales</h1> 
                        <p:separator/>
                        <div class="history">  <!--comienzo Redes Sociales del footer-->
                            <div >
                                <a class="btnM" href="#"  >
                                    <i class="fab fa-facebook-f"  ></i>
                                </a>
                                <a class="btnM" href="#">
                                    <i class="fab fa-twitter"></i>
                                </a>
                                <a class="btnM" href="#">
                                    <i class="fab fa-google"></i>
                                </a>
                                <a class="btnM" href="#">
                                    <i class="fab fa-instagram"></i>
                                </a>
                                <a class="btnM" href="#">
                                    <i class="fab fa-youtube"></i>
                                </a>
                            </div>        
                        </div>             <!--FIn Redes Sociales del footer-->    
                        <p:separator/>
                    </div>
                    <div class="box-footer"> <!--comienzel slider del footer-->
                        <h1>Galeria</h1> 
                        <p:separator/>
                        <div id="slider">
                            <figure>
                                <p:link title="Ir a la noticia" href="https://www.elsalvador.com/fotogalerias/noticias-fotogalerias/575437/imagenes-historicas-de-la-cruz-roja-salvadorena-en-su-134-aniversario/">
                                    <img src="#{request.contextPath}/resources/slider/imgmini1.png" />    
                                    <img src="#{request.contextPath}/resources/slider/imgmini2.jpg" />
                                    <img src="#{request.contextPath}/resources/slider/imgmini3.JPG" />
                                    <img src="#{request.contextPath}/resources/slider/imgmini4.jfif" />
                                    <img src="#{request.contextPath}/resources/slider/imgmini5.png" />

                                </p:link>
                            </figure>
                        </div>
                    </div>
                    <div class="copy-right"> <!--comienza el copyright-->
                        <p:separator/>
                        <h3 >Sistema de Control de Asistencia Copyright © 2019. Todos los derechos reservados</h3>
                        <p:separator/><br/>
                    </div>
                </div> 
            </div>   
        </div>
    </h:body>
</html>